config/routes.rb
Makeitsnappy::Application.routes.draw do
  
  root to: 'questions#index'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]
  resources :questions, except: [:new] do
    resources :answers, only: [:create]
  end

  match '/register', to: 'users#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/your_questions', to: 'questions#your_questions'
  match '/search', to: 'questions#search'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  attr_accessible :body

  validates :body, presence: true,
  								 length: { in: 2..255 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  attr_accessible :body, :solved

  validates :body, presence: true,
  								 length: { in: 10..255 }
  validates :solved, inclusion: { in: [true, false] }

  def self.unsolved(params)
  	where(solved: false).paginate(page: params[:page], order: 'created_at DESC', per_page: 3)
  end

  def self.search(params)
  	where("body LIKE ?", "%#{params[:keyword]}%").paginate(page: params[:page], order: 'created_at DESC', per_page: 3)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
  has_many :answers
  attr_accessible :username, :password, :password_confirmation

  has_secure_password

  validates :username, presence: true, uniqueness: { case_sensitive: false},
  										 length: { in: 4..12 }, 
  										 format: { with: /^[a-z][a-z0-9]*$/, message: "only lower case letters and numbers" } 

  validates :password, length: { in: 4..8 }
  validates :password_confirmation, length: { in: 4..8 }

  def your_questions(params)
  	questions.paginate(page: params[:page], order: 'created_at DESC', per_page: 3)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_filter :auth, only: [:create]

	def create
		@question = Question.find(params[:question_id])
		@answer = @question.answers.build(params[:answer])
		@answer.user = current_user

		if @answer.save
			flash[:success] = "Your anser was posted"
			redirect_to @question
		else
			@question = Question.find(params[:question_id])
			render 'questions/show'
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method [:current_user, :logged_in?]

  protected

  	def login(user)
  		session[:user_id] = user.id
  	end

  	def current_user
  		current_user ||= User.find(session[:user_id]) if session[:user_id]
  	end

  	def logged_in?
  		!current_user.nil?
  	end

    def auth
      redirect_to login_url, alert: 'You must login first' unless logged_in?
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_filter :auth, only: [:create, :your_questions, :edit, :update]

  def index
  	@question = Question.new
  	@questions = Question.unsolved(params)
  end

  def create
  	@question = current_user.questions.build(params[:question])
  	if @question.save
  		flash[:success] = 'Your Q was posted'
  		redirect_to @question
  	else
  		@questions = Question.unsolved(params)
  		render 'index'
  	end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def your_questions
    @questions = current_user.your_questions(params)
  end

  def edit
    @question = current_user.questions.find(params[:id])
  end

  def update
    @question = current_user.questions.find(params[:id])

    if @question.update_attributes(params[:question])
      flash[:success] = "Update Succesful!"
      redirect_to @question
    else
      render 'edit'
    end
  end

  def search
    @questions = Question.search(params)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_username(params[:session][:username])
  	if user && user.authenticate(params[:session][:password])
  		login user
  		flash[:success] = 'Logged In!'
  		redirect_to root_url
  	else
  		flash.now[:error] = 'Incorrect login'
  		render 'new'
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      login @user
  		flash[:success] = "Thanks for registering"
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

	def on_your_questions_page?
		action_name == 'your_questions'
	end

	def display_solved(question)
		(question.solved) ? ' - (Solved) ' : ''
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<li>
	<%= answer.body %> - by <%= answer.user.username.capitalize %>
</li>

app/views/answers/_answer_form.html.erb
<%= form_for([@question, @answer]) do |f| %>
	<%= render 'common/form_errors', object: @answer %>

	<p>
		<%= f.label :body, "Answer" %>
		<%= f.text_field :body %>
		<%= f.submit "Post Answer" %>
	</p>
<% end %>

app/views/common/_form_errors.html.erb
<% if object.errors.any? %>
	<ul id="form-errors">
		<% object.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

app/views/common/_search_form.html.erb
<%= form_tag(search_path, method: 'get') do %>
	<%= text_field_tag :keyword, 'Search', size: '20', id: 'keyword' %>
	<%= submit_tag "Search" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
	<div id="header">
		<%= link_to "Snappy Q&A", root_path %>
		<div id="searchbar">
			<%= render 'common/search_form' %>
		</div><!-- end searchform -->
	</div><!-- end header -->
	<div id="nav">
		<ul>
			<li>
				<%= link_to "Home", root_path %>
			</li>

			<% if logged_in? %>
				<li>
					<%= link_to "Your Q's", your_questions_path %>
				</li>
				<li>
					<%= link_to "Logout (#{current_user.username})", logout_path, method: 'delete' %>
				</li>
			<% else %>
				<li>
				<%= link_to "Register", register_path %>
				</li>
				<li>
				<%= link_to "Login", login_path %>
				</li>
			<% end %>
		</ul>
	</div>

	<div id="content">
		<% flash.each do |key, value| %>
			<p id="message"><%= value %></p>
		<% end %>

		<%= yield %>
	</div>
	<div id="footer"> 
		&copy; Snappy Q&A <%= Date.today.year %>
	</div>
</div>

</body>
</html>

app/views/questions/_question.html.erb
<li>
	<%= link_to truncate(question.body, length: 35), question %> by
	<%= question.user.username.capitalize %> 

	<% if on_your_questions_page? %>
		<%= display_solved(question) %> - <%= link_to 'Edit', edit_question_path(question) %>
	<% end %>

	- (<%= pluralize(question.answers.count, 'answer') %>)
</li>

app/views/questions/_question_form.html.erb
<%= form_for(@question) do |f| %>
	<%= render 'common/form_errors', object: @question %>

	<p>
		<%= f.label :body, "Question" %><br>
		<%= f.text_field :body %>

		<%= f.submit "Ask a Question" %>
	</p>
<% end %>

app/views/questions/edit.html.erb
<%= provide(:title, 'Edit Your Q') %>

<h1>Edit your Q</h1>

<%= form_for(@question) do |f| %>
	<%= render 'common/form_errors', object: @question %>

	<p>
		<%= f.label :body %><br>
		<%= f.text_field :body %>
	</p>

	<p>
		<%= f.label :solved %>
		<%= f.check_box :solved %>
	</p>

	<p>
		<%= f.submit "Update" %>
	</p>
<% end %>

app/views/questions/index.html.erb
<%= provide(:title, "Snappy Q&A") %>

<div id="ask">
	<h1>Ask a Question</h1>

	<% if logged_in? %>
		<%= render 'question_form' %>
	<% else %>
		<p>Please login to ask or answer questions</p>
	<% end %>

</div><!-- end ask -->

<div id="questions">
	<h2>Unsolved Q's</h2>
	<% if @questions.any? %>
		<ul>
			<%= render @questions %>
		</ul>
		<%= will_paginate %>
	<% else %>
		<p>No Q's yet!</p>
	<% end %>
</div><!-- end questions -->

app/views/questions/search.html.erb
<%= provide(:title, 'Search Results') %>
<h1>Search Results</h1>

<% if @questions.any? %>
	<ul>
		<%= render @questions %>
	</ul>
	<%= will_paginate %>
<% else %>
	<p>Nothing found, try a different search</p>
<% end %>

app/views/questions/show.html.erb
<%= provide(:title, "View Question") %>

<h1>
	<%= @question.user.username.capitalize %> asks:
</h1>

<p>
	<%= @question.body %>
</p>

<div id="answers">
	<h2>Answers</h2>

	<% if @question.answers.any? %>
		<ul>
			<%= render @question.answers %>
		</ul>
	<% else %>
		<p>No answers yet..</p>
	<% end %>

</div><!-- end answers -->

<div id="post-answer">
	<h2>Answer this Q</h2>

	<% if logged_in? %>
		<%= render 'answers/answer_form' %>
	<% else %>
		<p>Please login to post an answer</p>
	<% end %>

</div><!-- end post-answer -->

app/views/questions/your_questions.html.erb
<%= provide(:title, 'Your Questions') %>

<h1>Your Q's</h1>

<% if @questions.any? %>
	<ul>
		<%= render @questions %>
	</ul>
	<%= will_paginate %>
<% else %>
	<p>You've not posted any questions yet.</p>
<% end %>

app/views/users/new.html.erb
<%= provide(:title, "Snappy Q&A - Register") %>

<h1>Register</h1>

<%= form_for(@user) do |f| %>
	<%= render 'common/form_errors', object: @user %>

	<p>
		<%= f.label :username %><br>
		<%= f.text_field :username %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation, 'Confirm' %><br>
		<%= f.password_field :password_confirmation %>
	</p>

	<p>
		<%= f.submit "Register" %>
	</p>
<% end %>